export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ING_FETCH_FAILED = 'ING_FETCH_FAILED';

export const PLACE_ORDER_SUCCESS ='PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_ERROR =   'PLACE_ORDER_ERROR';
export const PLACE_ORDER_START = 'PLACE_ORDER_START';

export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOG_OUT ='LOG_OUT';

export const AUTH_REDIRECT_URL = 'AUTH_REDIRECT_URL';